spring:
  jpa:
    show-sql: true
  #datasource:
  #  platform: oracle
  #  url: jdbc:oracle:thin:@lx707:1521:dbt355
  #  username: gldadmin
  #  password: tg1d_adm
  #  driver-class-name: oracle.jdbc.driver.OracleDriver

gldadmin:
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@lx707:1521:dbt355
    username: gldadmin
    password: tg1d_adm
    driver-class-name: oracle.jdbc.driver.OracleDriver

fineos:
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@lx707:1521:dbt355
    username: fineos
    password: tf1ne08_usr
    driver-class-name: oracle.jdbc.driver.OracleDriver

#fineossec:
  #datasource:
    #platform: oracle
    #url: jdbc:oracle:thin:@lx707:1521:dbt355
    #username: fineossec
    #password: tf1ne08_sec
    #driver-class-name: oracle.jdbc.driver.OracleDriver

rest:
  security:
    users:
      - userId: gldsvc
        password: f8nYmVw/ch3xelbgUVknLw==
        roles: "USER"
