spring:
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@lx707:1521:dbt355
    username: gldadmin
    password: tg1d_adm
    driver-class-name: oracle.jdbc.driver.OracleDriver

rest:
  security:
    users:
      - userId: gldsvc
        password: f8nYmVw/ch3xelbgUVknLw==
        roles: "USER"
