spring:
  jpa:
    show-sql: true
  #datasource:
  #  platform: oracle
  #  url: jdbc:oracle:thin:@lx707:1521:dbt355
  #  username: gldadmin
  #  password: tg1d_adm
  #  driver-class-name: oracle.jdbc.driver.OracleDriver

gldadmin:
  datasource:
    platform: oracle
    jndi-name: java:comp/env/jdbc/gldref
    url: jdbc:oracle:thin:@lx707:1521:dbt355
    username: gldadmin
    password: v2JGWwhsTcm3RGAEqvBPTQ==
    driver-class-name: oracle.jdbc.driver.OracleDriver

fineos:
  datasource:
    platform: oracle
    jndi-name: java:comp/env/jdbc/fineosappref
    url: jdbc:oracle:thin:@lx707:1521:dbt355
    username: fineos
    password: BX1L0vmaEpSoInPxR+H0Gg==
    driver-class-name: oracle.jdbc.driver.OracleDriver

#fineossec:
  #datasource:
    #platform: oracle
    #url: jdbc:oracle:thin:@lx707:1521:dbt355
    #username: fineossec
    #password: tf1ne08_sec
    #driver-class-name: oracle.jdbc.driver.OracleDriver

rest:
  security:
    users:
      - userId: gldsvc
        password: f8nYmVw/ch3xelbgUVknLw==
        roles: "USER"
