spring:
  application:
    name: 'MyRestTest'
    version: 1.0
  profiles:
    active: ${WAS_ENV:Unit}

security:
  user:
    name: us3rNam3
    password: pazzword
    roles: ACTUATOR
# The line below unsecures the application endpoints.
# This should be removed from production profiles.
  ignored: /**

# Actuator endpoints are secured by default in Spring 1.5
# The configuration below unsecures those endpoints.
# This should be removed from production profiles.
management:
  security:
    enabled: false


swagger:
  api-info:
    title: 'MyRestTest'
    desc: 'test'
    creator: 'req69775'
    url-desc: 'API Documentation'
    url: 'com.mutualofomaha.gld.myresttest.controller'
